/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:7003b8a0-18f9-4c78-83a4-24caf57a2988",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_63I9alose",
    "aws_user_pools_web_client_id": "2v76tkedmk4nnp1kkgehhdfma4",
    "oauth": {}
};


export default awsmobile;
